const { chromium } = require('playwright');
(async()=>{const q=process.argv[2]||'2',out=process.argv[3]||'/tmp/claude-0/shot.png',zoom=process.argv[4];const b=await chromium.launch();const p=await b.newPage({viewport:{width:1400,height:850}});
const errs=[];p.on('pageerror',e=>errs.push(''+e));
await p.addInitScript(q=>localStorage.setItem('auld-world.gfx',q),q);
await p.goto('http://localhost:8123/');await p.waitForTimeout(2500);
await p.mouse.click(700,425);await p.waitForTimeout(800);
let r=await p.locator('#hSkirmish').boundingBox();await p.mouse.click(r.x+r.width/2,r.y+r.height/2);await p.waitForTimeout(600);
await p.click('#mBegin');await p.waitForTimeout(1200);
await p.evaluate(()=>{const g=window.__seven.game;window.__seven.ui.objHidden=true;document.getElementById('objectives')?.classList.add('hidden');});
const ms=+process.argv[5]||0;
await p.waitForTimeout(1500);
const t0=await p.evaluate(()=>new Promise(r=>{let n=0,s=performance.now();const f=()=>{n++;if(performance.now()-s>2000)r(n/2);else requestAnimationFrame(f)};requestAnimationFrame(f)}));
console.log('fps',t0);
await p.screenshot({path:out});console.log('errs',errs);await b.close();})();
